### ISSUE TITLE
Unsupported connection setting "DATABASE_TO_LOWER"

### ISSUE THREAD

**Issue by cassianomansano** [wise-coders/dbf-jdbc-driver#12]
When I start the symmetricds application, this error occurs, is there anything I can do?

AbstractSymmetricEngine - Initializing connection to database
Jan 07, 2024 8:32:25 PM com.wisecoders.dbschema.dbf.JdbcDriver getConnection

INFO: Create H2 database 'jdbc:h2:file:~/.DbSchema/jdbc-dbf-cache/4fcaccd23defd13fb448def2adb30e38;database_to_lower=true;case_insensitive_identifiers=true'

JdbcDriver - Create H2 database 'jdbc:h2:file:~/.DbSchema/jdbc-dbf-cache/4fcaccd23defd13fb448def2adb30e38;database_to_lower=true;case_insensitive_identifiers=true'

**Could not get a connection to the database: Cannot create PoolableConnectionFactory (Unsupported connection setting "DATABASE_TO_LOWER" [90113-176]).**  
Waiting for 10 seconds before trying to connect to the database again.

**Comment by wise-coders** [comment]
Thank you for reporting this. We have published right now a new driver, with updated libraries and a fix for this parameter. Could you please give it a try? Our tests are working fine, but it is still possible to get issues. Please write a short reply about the results.
