### ISSUE TITLE
Reload fails: Column "file_name" not found

### ISSUE THREAD

**Issue by jeremyross** [wise-coders/dbf-jdbc-driver#6]
When attempting the reload command, I get:

```
Column "file_name" not found
DELETE FROM dbs_meta_files WHERE file_name=?
```

f96f0b3c31316c change the expected column name from `file_path` to `file_name`. But the column is still `file_path`.

**Comment by wise-coders** [comment]
Thank you for writing about this. We fixed the problem, pushed the change.
Publishing the artifact fails. We are checking for a solution.

**Comment by wise-coders** [comment]
Now we had a new attempt which succeeded. Please give it a try.
