### ISSUE TITLE
Are memo fields supported?

### ISSUE THREAD

**Issue by jeremyross** [wise-coders/dbf-jdbc-driver#9]
When I connect to a dbf+fpt file, I see that large varchar columns are created for the memo field, but the data doesn't seem to be imported. All records have null for memo fields.

**Comment by wise-coders** [comment]
Memofields are supported. There could be an issue with certain versions of the DBF file. Could you please send us a sample DBF file ( something simple, to test ).

**Comment by jeremyross** [comment]
Unfortunately the data is all confidential, so I can't share. 

The data file is a .DBF file, and the memo file has the same name as the data file, but with the extension .FPT. Is this what is expected?

**Comment by jeremyross** [comment]
Info from file system:
```
> file mbrleav.DBT 
mbrleav.DBT: FoxPro FPT, blocks size 64, next free block index 3653, field type 1, field length 99
```

**Comment by wise-coders** [comment]
We use this library to read the DBF files:

com.github.albfernandez:javadbf:1.14.0

Probably you already saw it.

Best regards,
 Dragos Pruteanu

> On Thursday, July 27, 2023 at 6:30:57 PM, DaveDevelop wrote:
>
> FPT files are a little different than DBT. Do you know if FPT files are supported?
> —
> Reply to this email directly, [1] view it on GitHub, or [2] unsubscribe.
> You are receiving this because you commented.Message ID:

[1] https://github.com/wise-coders/dbf-jdbc-driver/issues/9#issuecomment-1653960055
